### ISSUE TITLE
Fast-downward executable missing on Windows platform

### ISSUE THREAD

**Issue by fteicht** [aiplan4eu/up-fast-downward#15]
After installing up-fast-downward, either with `pip install unified-planning[fast-downward]` or with `pip install up-fast-downward`, the fast downward executable is absent under `$PATH_TO_PYTHON_INSTALLATION\Lib\site-packages\up_fast_downward\downward`.

When solving a UP problem with the following command:
```
with OneshotPlanner(name='fast-downward') as planner:
    result = planner.solve(problem, output_stream=sys.stdout)
```
I get the following message:

```
  *** Credits ***
  * In operation mode `OneshotPlanner` at line 549 of `$PATH_TO_PYTHON_INSTALLATION\lib\site-packages\unified_planning\shortcuts.py`, you are using the following planning engine:
  * Engine name: Fast Downward
  * Developers:  Uni Basel team and contributors (cf. https://github.com/aibasel/downward/blob/main/README.md)
  * Description: Fast Downward is a domain-independent classical planning system.

INFO     planner time limit: None
Could not find build 'release' at $PATH_TO_PYTHON_INSTALLATION\lib\site-packages\up_fast_downward\downward\builds\release\bin. Please run './build.py release'.
INFO     planner memory limit: None

INFO     Running translator.
RESULT: status: INTERNAL_ERROR
engine: Fast Downward (with optimality guarantee)
plan: None
```
It shows that the fast-downward executable is missing. I do not have any `builds `folder in `$PATH_TO_PYTHON_INSTALLATION\lib\site-packages\up_fast_downward\downward`.

If it is the intented behaviour on Windows, I think that it should be mentioned in the package documentation.

**Comment by roeger** [comment]
@fteicht Thanks for reporting this, I had a bug in the github workflow for building the windows wheel. This should be fixed in version 0.3.1, which you now get if you install up-fast-downward separately. I also made a pull request to use this version if installed together with unified planning, so this should be resolved soon.

To catch such problems before deployment in the future, I also extended the workflow with a small test.
